from sqlalchemy import Boolean, Column, DateTime, ForeignKey, Integer, PrimaryKeyConstraint, String
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from app.db.encrypted_types import EncryptedString
from app.db.session import Base


class LocalSession(Base):
    """Stores local app activity sessions recorded on a user's machine by the tracker.

    Each row represents a period of time spent focused on a specific application.
    The `id` field is a unique identifier generated by the local tracker (not by the backend).

    Key details:
    - Unique Key: Rows are identified by both `user_id` and `id` together. Combining user_id
      and session id ensures one user's data can never overwrite another user's session.
    - End Status: The fields `ended_at` and `end_reason` are required in this database table,
      meaning only fully completed sessions are saved here.
    - End Reason: `end_reason` is stored as a simple text string rather than a strict enum.
      While standard reasons (like idle, sleep, or app switch) exist, storing it as plain text
      ensures new or unexpected reason strings from the tracker are accepted without breaking.
    """

    __tablename__ = "local_sessions"
    __table_args__ = (PrimaryKeyConstraint("user_id", "id"),)

    id = Column(UUID(as_uuid=True), nullable=False)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    bundle_id = Column(String, nullable=False)
    app_name = Column(String, nullable=False)
    window_title = Column(String, nullable=True)
    project_path = Column(String, nullable=True)
    context_detail = Column(String, nullable=True)
    started_at = Column(DateTime(timezone=True), nullable=False)
    ended_at = Column(DateTime(timezone=True), nullable=False)
    end_reason = Column(String, nullable=False)
    is_idle = Column(Boolean, nullable=False, default=False)
    synced_at = Column(DateTime(timezone=True), nullable=False, server_default=func.now())

    user = relationship("User", back_populates="local_sessions")


class TrackerDevice(Base):
    """Represents an authenticated local tracker installation for a user.

    The device_id is a UUID generated by the local tracker on first run.
    The token is an encrypted long-lived API token used for background syncs.
    """
    __tablename__ = "tracker_devices"

    id = Column(Integer, primary_key=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    device_id = Column(UUID(as_uuid=True), nullable=False, unique=True, index=True)
    name = Column(String, nullable=False)
    token = Column(EncryptedString, nullable=False)
    created_at = Column(DateTime(timezone=True), nullable=False, server_default=func.now())

    user = relationship("User")


class TrackerSyncState(Base):
    """Stores the high-water mark (last_synced_at) for a specific tracker device.

    This ensures that when a tracker syncs, it only sends new or updated sessions
    since this checkpoint. We key this by device_id to support a user having
    multiple trackers (e.g. desktop and laptop) without them overwriting each other's checkpoints.
    """
    __tablename__ = "tracker_sync_states"
    __table_args__ = (PrimaryKeyConstraint("user_id", "device_id"),)

    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    device_id = Column(UUID(as_uuid=True), ForeignKey("tracker_devices.device_id", ondelete="CASCADE"), nullable=False)
    last_synced_at = Column(DateTime(timezone=True), nullable=False)
    updated_at = Column(DateTime(timezone=True), nullable=False, server_default=func.now(), onupdate=func.now())

    user = relationship("User")
