from sqlalchemy import Boolean, Column, DateTime, ForeignKey, Integer, PrimaryKeyConstraint, String
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from app.db.session import Base


class LocalSession(Base):
    """Stores local app activity sessions recorded on a user's machine by the tracker.

    Each row represents a period of time spent focused on a specific application.
    The `id` field is a unique identifier generated by the local tracker (not by the backend).

    Key details:
    - Unique Key: Rows are identified by both `user_id` and `id` together. Combining user_id
      and session id ensures one user's data can never overwrite another user's session.
    - End Status: The fields `ended_at` and `end_reason` are required in this database table,
      meaning only fully completed sessions are saved here.
    - End Reason: `end_reason` is stored as a simple text string rather than a strict enum.
      While standard reasons (like idle, sleep, or app switch) exist, storing it as plain text
      ensures new or unexpected reason strings from the tracker are accepted without breaking.
    """

    __tablename__ = "local_sessions"
    __table_args__ = (PrimaryKeyConstraint("user_id", "id"),)

    id = Column(UUID(as_uuid=True), nullable=False)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    bundle_id = Column(String, nullable=False)
    app_name = Column(String, nullable=False)
    window_title = Column(String, nullable=True)
    started_at = Column(DateTime(timezone=True), nullable=False)
    ended_at = Column(DateTime(timezone=True), nullable=False)
    end_reason = Column(String, nullable=False)
    is_idle = Column(Boolean, nullable=False, default=False)
    synced_at = Column(DateTime(timezone=True), nullable=False, server_default=func.now())

    user = relationship("User", back_populates="local_sessions")
