"""add entry_versions table

Revision ID: 283e0bebe749
Revises: c7e52807067a
Create Date: 2026-07-31 18:46:03.418510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '283e0bebe749'
down_revision: Union[str, None] = 'c7e52807067a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('ai_draft', 'human_approved', 'human_revision', name='entry_version_source'), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entry_versions_entry_id'), 'entry_versions', ['entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entry_versions_entry_id'), table_name='entry_versions')
    op.drop_table('entry_versions')
    # drop_table alone leaves the native enum type behind -- without this, a
    # downgrade followed by a re-upgrade fails with "type already exists".
    sa.Enum(name='entry_version_source').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
