"""add external_id to events with unique constraint

Revision ID: 92c056e2de9f
Revises: fa01e025bdf2
Create Date: 2026-07-07 12:28:00.237667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92c056e2de9f'
down_revision: Union[str, None] = 'fa01e025bdf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('external_id', sa.String(), nullable=True))
    op.create_unique_constraint('uq_events_user_source_type_external_id', 'events', ['user_id', 'source', 'type', 'external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_events_user_source_type_external_id', 'events', type_='unique')
    op.drop_column('events', 'external_id')
    # ### end Alembic commands ###
