"""entries content jsonb, integration metadata, user default channel

Revision ID: fa01e025bdf2
Revises: 5eea9c691db5
Create Date: 2026-07-04 12:10:31.470998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa01e025bdf2'
down_revision: Union[str, None] = '5eea9c691db5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entries', 'content',
               existing_type=sa.TEXT(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               postgresql_using='content::jsonb',
               existing_nullable=False)
    op.add_column('integrations', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('default_channel', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'default_channel')
    op.drop_column('integrations', 'metadata')
    op.alter_column('entries', 'content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               postgresql_using='content::text',
               existing_nullable=False)
    # ### end Alembic commands ###
